# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_(self):
        self.driver.get("https://jobs.bytedance.com/")
        self.driver.set_window_size(1052, 654)
        self.driver.find_element(By.CSS_SELECTOR, ".atsx-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".atsx-input").send_keys("测试工程师")
        self.driver.find_element(By.CSS_SELECTOR, ".atsx-input").send_keys(Keys.ENTER)

        res_element = self.driver.find_element(By.CSS_SELECTOR, ".atsx-input")
        assert "测试工程师" == res_element.text